### ISSUE TITLE
ClassyNaming 1.1.0 doesn't work with VS Code 1.13.0

### ISSUE THREAD

**Issue by cateyes99** [reflectiondm/vscode-classyNaming#3]
- VSCode Version: 1.13.0
- OS Version: OS X EI Capitan 10.11.3

After upgrading to ClassyNaming 1.1.0 from 1.0.0, it cause my VS Code 1.13.0 almost has no intellisense at all :(

1.1.0 does not work since VS Code 1.10.2 on my Mac, but 1.0.0 does, so I downgraded back to 1.0.0 since 1.1.0 came out.

**Comment by reflectiondm** [comment]
@cateyes99 Thanks for the feedback, I'll check that.

**Comment by peter-nham** [comment]
I've had the same issue, quick suggestions don't pop up.

You can only trigger manual intellisense with control + space

**Comment by JMPSequeira** [comment]
Same here.

**Comment by reflectiondm** [comment]
@cateyes99 @petern-sc @JMPSequeira Thanks for the feedback, guys. Sorry that fix took so much time, but now it should be working again. Please check updated extension.
